### ISSUE TITLE
Thanks for Sharing!

### ISSUE THREAD

**Issue by Statgnome** [daniel112/openai-hackathon-realtime-translation#1]
I am just getting into using openAI stuff to try and make an interactive game. I saw your post on Reddit, and I hope to learn from your project. Thanks for sharing your work!

**Comment by daniel112** [comment]
Thanks for stopping by. I'm glad you have found this even a little bit inspiring. 

If you have any questions or regarding the tools I used in this project or how you might want to integrate some of this onto your own project let me know!
